apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: predictor
  name: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: predictor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: predictor
    spec:
      containers:
        - image: flight-predictor_spark-predictor
          name: flight-predictor-predictor
          ports:
            - containerPort: 4040
          resources: {}
      restartPolicy: Always
status: {}
