apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  labels: 
    app: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - image: martinigoyanes/k8s-spark-flight-predictor
        name: predictor
        ports:
        - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  selector:
    app: predictor
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30002