FROM mongo:5.0.3

RUN apt-get update
RUN apt install -y curl
# Download data to provision database
RUN curl -Lko /origin_dest_distances.jsonl http://s3.amazonaws.com/agile_data_science/origin_dest_distances.jsonl
COPY setup_mongodb.sh /

CMD ["./setup_mongodb.sh"]